// tailwind.config.js (new v4 format)
export default {
    content: [
      './src/**/*.{js,ts,jsx,tsx,mdx}',
      './components/**/*.{js,ts,jsx,tsx,mdx}',
      './shared/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    safelist: [
      // Button variants
      'bg-primary-500', 'bg-primary-600', 'text-white', 'hover:bg-primary-600', 'hover:shadow-lg',
      'bg-secondary-500', 'bg-secondary-600', 'hover:bg-secondary-600',
      'border-2', 'border-primary-500', 'text-primary-500', 'hover:bg-primary-500', 'hover:text-white',
      'text-primary-500', 'hover:bg-primary-50', 'hover:text-primary-600',
      'underline-offset-4', 'hover:underline',
      // Card variants
      'bg-white', 'border-gray-200', 'shadow-card', 'hover:shadow-card-hover',
      'border-gray-300', 'hover:border-primary-300',
      'bg-transparent', 'border-transparent', 'hover:bg-gray-50',
      'bg-gradient-to-br', 'from-primary-50', 'to-secondary-50', 'border-primary-200',
      'shadow-lg', 'hover:shadow-xl', 'transform', 'hover:-translate-y-1', 'transition-all', 'duration-200',
      'cursor-pointer',
      // Tag/Badge/Alert
      'rounded-full', 'px-2.5', 'py-0.5', 'text-xs', 'font-semibold',
      'bg-success-500', 'bg-warning-500', 'bg-error-500', 'bg-info-500',
      'text-success-600', 'text-warning-600', 'text-error-600', 'text-info-600',
      'border-success-500', 'border-warning-500', 'border-error-500', 'border-info-500',
      'hover:bg-success-600', 'hover:bg-warning-600', 'hover:bg-error-600', 'hover:bg-info-600',
      // Misc
      'rounded-xl', 'rounded-2xl', 'rounded-3xl',
      'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl', 'text-5xl',
      'font-bold', 'font-medium', 'font-semibold',
      'text-graphite-500', 'text-graphite-600', 'text-graphite-700',
      'bg-gray-100', 'text-gray-700', 'text-gray-500',
      'bg-primary-50', 'text-primary-600', 'bg-secondary-50', 'text-secondary-600',
      'w-full', 'h-full', 'flex', 'items-center', 'justify-center', 'gap-2', 'gap-4',
      'transition-colors', 'duration-200',
    ],
    theme: {
      extend: {
        // Map CSS custom properties to Tailwind theme colors
        colors: {
          primary: {
            50: 'var(--color-primary-50)',
            100: 'var(--color-primary-100)',
            200: 'var(--color-primary-200)',
            300: 'var(--color-primary-300)',
            400: 'var(--color-primary-400)',
            500: 'var(--color-primary-500)',
            600: 'var(--color-primary-600)',
            700: 'var(--color-primary-700)',
            800: 'var(--color-primary-800)',
            900: 'var(--color-primary-900)',
          },
          secondary: {
            50: 'var(--color-secondary-50)',
            100: 'var(--color-secondary-100)',
            200: 'var(--color-secondary-200)',
            300: 'var(--color-secondary-300)',
            400: 'var(--color-secondary-400)',
            500: 'var(--color-secondary-500)',
            600: 'var(--color-secondary-600)',
            700: 'var(--color-secondary-700)',
            800: 'var(--color-secondary-800)',
            900: 'var(--color-secondary-900)',
          },
          graphite: {
            50: 'var(--color-graphite-50)',
            100: 'var(--color-graphite-100)',
            200: 'var(--color-graphite-200)',
            300: 'var(--color-graphite-300)',
            400: 'var(--color-graphite-400)',
            500: 'var(--color-graphite-500)',
            600: 'var(--color-graphite-600)',
            700: 'var(--color-graphite-700)',
            800: 'var(--color-graphite-800)',
            900: 'var(--color-graphite-900)',
          },
          gray: {
            50: 'var(--color-gray-50)',
            100: 'var(--color-gray-100)',
            200: 'var(--color-gray-200)',
            300: 'var(--color-gray-300)',
            400: 'var(--color-gray-400)',
            500: 'var(--color-gray-500)',
            600: 'var(--color-gray-600)',
            700: 'var(--color-gray-700)',
            800: 'var(--color-gray-800)',
            900: 'var(--color-gray-900)',
            950: 'var(--color-gray-950)',
          },
          success: {
            50: 'var(--color-success-50)',
            100: 'var(--color-success-100)',
            500: 'var(--color-success-500)',
            600: 'var(--color-success-600)',
            700: 'var(--color-success-700)',
          },
          warning: {
            50: 'var(--color-warning-50)',
            100: 'var(--color-warning-100)',
            500: 'var(--color-warning-500)',
            600: 'var(--color-warning-600)',
            700: 'var(--color-warning-700)',
          },
          error: {
            50: 'var(--color-error-50)',
            100: 'var(--color-error-100)',
            500: 'var(--color-error-500)',
            600: 'var(--color-error-600)',
            700: 'var(--color-error-700)',
          },
          info: {
            50: 'var(--color-info-50)',
            100: 'var(--color-info-100)',
            500: 'var(--color-info-500)',
            600: 'var(--color-info-600)',
            700: 'var(--color-info-700)',
          },
          background: 'var(--background)',
          foreground: 'var(--foreground)',
        },
        fontFamily: {
          inter: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        },
        fontSize: {
          'xs': ['0.75rem', { lineHeight: '1rem' }],
          'sm': ['0.875rem', { lineHeight: '1.25rem' }],
          'base': ['1rem', { lineHeight: '1.5rem' }],
          'lg': ['1.125rem', { lineHeight: '1.75rem' }],
          'xl': ['1.25rem', { lineHeight: '1.75rem' }],
          '2xl': ['1.5rem', { lineHeight: '2rem' }],
          '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
          '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
          '5xl': ['3rem', { lineHeight: '1' }],
          '6xl': ['3.75rem', { lineHeight: '1' }],
        },
        spacing: {
          '18': '4.5rem',
          '88': '22rem',
          '128': '32rem',
        },
        boxShadow: {
          'card': '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
          'card-hover': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
          'lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
          'xl': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        },
        borderRadius: {
          'xl': '0.75rem',
          '2xl': '1rem',
          '3xl': '1.5rem',
        },
        animation: {
          'fade-in': 'fadeIn 0.5s ease-in-out',
          'slide-up': 'slideUp 0.5s ease-out',
          'slide-down': 'slideDown 0.5s ease-out',
        },
        keyframes: {
          fadeIn: {
            '0%': { opacity: '0' },
            '100%': { opacity: '1' },
          },
          slideUp: {
            '0%': { transform: 'translateY(20px)', opacity: '0' },
            '100%': { transform: 'translateY(0)', opacity: '1' },
          },
          slideDown: {
            '0%': { transform: 'translateY(-20px)', opacity: '0' },
            '100%': { transform: 'translateY(0)', opacity: '1' },
          },
        },
      },
    },
    plugins: [
      require('@tailwindcss/forms'),
      require('@tailwindcss/typography'),
      require('@tailwindcss/aspect-ratio'),
    ],
  }