INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('a10d.info', 'a10d.info - Calendar Attendee Info', NULL, 'Get the emails of everyone you have met with from your calendar.', NULL, '/images/cal_screenshot.png', false, '2025-04-28T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('ai-image-recognition', 'AI Image Recognition Project', NULL, 'Training an EfficientNet-B3 Model to recognize specific patterns within images for matching to online product listings. Advanced machine learning project for e-commerce and inventory management applications.', NULL, '/images/ai_images.png', false, '2025-03-01T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('ai-text-processing-pipeline', 'AI Text Processing Pipeline', NULL, 'Leveraging AI to transform complex, unstructured text data about luxury products into comprehensive digital profiles without manual parsing code. Advanced ChatGPT API integration for automated data extraction.', NULL, '/images/ai_text_pipeline.png', false, '2025-03-01T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('barn-doors-for-sale-ecommerce-site', 'BarnDoors.ForSale', NULL, 'Co-founded an e-commerce platform specializing in barn doors for interior designers, contractors, and homeowners. Managed website design, marketing, order fulfillment, and customer support for growing business.', NULL, '/images/barn_door.png', false, '2020-04-20T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('building-user-event-management-tool', 'User and Event Management System', NULL, 'Using Python to build a comprehensive management system for worldwide user and event management, replacing spreadsheets with organized community building platform for global organization.', NULL, '/images/event_management.jpg', false, '2025-03-10T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('custom-excerpt-plugin', 'Custom Excerpt Admin Page WordPress Plugin', NULL, 'WordPress plugin that simplifies excerpt management through an intuitive admin interface, eliminating the need for code modifications. Complete control over post excerpts without coding knowledge.', NULL, '/images/wordpress.jpg', false, '2011-10-15T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('developer-experience', 'Developer Experience Improvement', NULL, 'Led SDK adoption improvements and enhanced developer experience at SendGrid. Increased SDK adoption rates through better API design, documentation, and developer-centric processes using product-led growth strategies.', NULL, '/images/dev_experience.png', false, '2018-01-15T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('ignite-denver', 'Ignite Denver', 'http://www.ignitedenver.org', 'Community-focused event series providing a public forum for sharing ideas through fast-paced, structured presentations. 5-minute talks with 20 auto-advancing slides, connecting diverse speakers with broad audiences in Denver.', NULL, '/images/ignite_denver.png', false, '2008-01-01T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('product-led-growth-temporal', 'Product-Led Growth at Temporal', 'https://temporal.io', 'Implemented a product-led growth strategy for a cloud-based workflow platform.', NULL, '/images/plg.png', false, '2024-03-08T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('project-management-dashboard-202503', 'Project Management Dashboard', 'https://github.com/user/project-dashboard', 'Built a dashboard integrating four task management systems for a public company.', NULL, '/images/pm_dashboard.png', false, '2024-03-08T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('software-analysis-tool', 'Software Analysis Tool', NULL, 'AI-powered tool that provides insights and non-obvious information about GitHub repositories, integrating artificial intelligence for deeper code analysis, pattern recognition, and improvement opportunities.', NULL, '/images/software_analysis.png', false, '2024-11-01T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('south-denver-plumber', 'SouthDenverPlumber.com - A local plumber''s Website', NULL, 'Professional website built for Frank Santilli''s plumbing business serving South Denver areas, featuring service details, testimonials, and client communication tools. Modern React-based design with mobile-first approach.', NULL, '/images/cal_screenshot.png', false, '2025-05-07T00:00:00.000Z');
INSERT INTO projects (slug, title, url, description, features, image, show_on_offers_page, created_at)
VALUES ('wordpress-testimonials', 'WordPress Testimonials Plugin', NULL, 'WordPress plugin designed to easily add and manage testimonials throughout a website, created as a replacement for a discontinued plugin. Features custom post types, shortcodes, and widgets for flexible testimonial display.', NULL, '/images/wordpress.jpg', false, '2012-01-15T00:00:00.000Z');
